host: "0.0.0.0"
port: 3000
grpcport: 50051
storage: "Postgres" # or MapStorage
dburi: "postgres://golendar:golendar@localhost:5432"
notify: 15 # minutes
mquri: "amqp://golendar:golendar@localhost:5672/"