version: '3.7'

services:

  integration_tests:
    build:
      context: ./
      dockerfile: ./tests/Dockerfile
    depends_on:
      - postgres
      - rabbitmq
      - api
      - notifications_sender
      - notifications_creator
    networks:
      - golendar_net