version: '3.7'

services:

  rabbitmq:
    image: "rabbitmq:3"
    hostname: rabbit_node_1
    ports:
      - "5672:5672"
    networks:
      - golendar_net
    env_file:
      - .env.dist

  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    networks:
      - golendar_net
    env_file:
      - .env.dist

networks:
  golendar_net:
    driver: "bridge"