version: '3.7'

services:

  rabbitmq:
    image: "rabbitmq:3"
    hostname: rabbitmq
    networks:
      - golendar_net
    env_file:
      - .env.dist

  postgres:
    image: "postgres"
    networks:
      - golendar_net
    env_file:
      - .env.dist

  api:
    restart: unless-stopped
    build: ./
    ports:
        - '3000:3000'
    depends_on:
        - postgres
        - rabbitmq
    networks:
      - golendar_net

  notifications_creator:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./cmd/daemons/creator/Dockerfile
    depends_on:
        - postgres
        - rabbitmq
        - api
    networks:
      - golendar_net

  notifications_sender:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./cmd/daemons/sender/Dockerfile
    depends_on:
        - postgres
        - rabbitmq
        - api
    networks:
      - golendar_net

networks:
  golendar_net:
    driver: "bridge"